### ISSUE TITLE
Clean up test data imported from au core 0.2.2-preview

### ISSUE THREAD

**Issue by dt-r** [hl7au/au-fhir-test-data#11]
1. Evaluate existing data sources from au core 0.2.2-preview.
2. Identify any that need to be removed.
3. Remove those, make any amendments necessary to update resource references and create cohesive sets

**Comment by StephThaoOng** [comment]
Done for the clinical test data. 
Done for Patient, Practitioner, PractitionerRole, Organisation, Location. For personas retained that were not derived from Services Australia (SA) data, they either had demographics not present in the SA data or had to be retained at present due to the multiple codings issue on the FHIR server.
