### ISSUE TITLE
PractitionerRole: enrich PractitionerRole.code to align to AU Base & AU Core

### ISSUE THREAD

**Issue by dt-r** [hl7au/au-fhir-test-data#22]
Services Australia provided PractitionerRoles come from ANZSCO which is allowed, but the coding preferred in AU Base & AU Core is from https://healthterminologies.gov.au/fhir/ValueSet/practitioner-role-1.

Add a 2nd coding from https://healthterminologies.gov.au/fhir/ValueSet/practitioner-role-1

**Comment by heathfrankel** [comment]
Ideally we would a full conceptMap of the ANZSCO codes for the SA data and implement these for all SA data, but at this time these records would be rejected by the SParked Smile CDR use to the outstanding multiple codings terminology validation error.
For now I have manually applied a few of these so that they will exist in the test data repo, but they will not get uploaded to the server.
For this reason I have not applied this to any of the PractitionerRoles used in other resources.
To demonstrate the use of the practitioner-role binding, I have one PractitionerRole, which is not derived from SA data and as such has no identifiers.

**Comment by heathfrankel** [comment]
PractitionerRole.code was previously using ANZSCO codes derived from Services Australia data. A limitation in Smile CDR stopped instances with a second coding so additional SCT coding was not provided.
This issue has now been resolved and several SCT codings now exist e.g. [PractitionerRole-nursepractitioner-mcleod-clinton.json](https://github.com/hl7au/au-fhir-test-data/blob/master/generated/PractitionerRole-nursepractitioner-mcleod-clinton.json)
There is also a Medicare Provider Number, specialty and a Location reference derived from Services Australia data.
