### ISSUE TITLE
Remove erroneous PractitionerRole, Practitioner, Organization and Location examples (auto imported from the old AU Core) from the test data

### ISSUE THREAD

**Issue by dbojicic** [hl7au/au-fhir-test-data#25]
The following examples have been imported from the old AU Core IG and should be removed from the test data: 
- PractitionerRole-nephrologist-levin-henry (removed from the IG and replaced with SA test data PractitionerRole-nephrologist-darleen-mackay)
- PractitionerRole-surgeon-david-surgeon (removed from the IG and replaced with PractitionerRole-surgeon-chau-fryer (SA test data))
- Practitioner-levin-henry (removed from the IG and replaced with Practitioner-darleen-mackay)
- Practitioner-surgeon-david (removed from the IG and replaced with Practitioner-chau-fryer (SA test data))
- Organization-dva-au
- Organization-health-au

These have been removed from the IG as well, I suggest removing them from the test data and using SA test data instead:
- PractitionerRole-retail-pharmacist
- PractitionerRole-sandyson-sandy-nurse
- PractitionerRole-gp-primary-peter
- Practitioner-primary-peter  
- PractitionerRole-np-nurse-nancy
- Practitioner-nurse-nancy
- Practitionecardiolor-cardy-igist
- Organization-hospital-au
- Organization-hospital-int
- Organization-pharmacy
- Location-pharmacy - remove existing and generate from SA test data 
- Location-au-hospital - remove existing and generate from SA test data 
- Location-au-hospital-pharm-out - remove existing and generate from SA test data
- Location-au-hospital-sw-physio - remove existing and generate from SA test data 

These have also been removed from the IG but are not included or partially included in the Services Australia provided PractitionerRoles, Practitioner or Organizations samples. Leaving it to you and how you reorganise the test data whether to keep these or not, noting that the test data does not need to be fully aligned with the IG.    
- PractitionerRole-audiologist-bradley-jill
- Practitioner-bradley-jill
- PractitionerRole-dietician-tan-patricia
- Organization-adv-hearing-care (Audiology service organization provided but not linked to a provider)

FYI, these IG examples have been updated following the above changes and may need to be updated in the test data:
- encounter-discharge-1.xml
- hearing-threshold-1.xml
- medicationrequest-paracetamol-codeine.xml
- medicationrequest-reaptan.xml
- procedure-dialysis.xml
- procedure-stentinsertion.xml

**Comment by heathfrankel** [comment]
PractitionerRole-nephrologist-levin-henry (removed from the IG and replaced with SA test data PractitionerRole-nephrologist-darleen-mackay) 
- PractitionerRole-nephrologist-levin-henry already removed
- PractitionerRole-nephrologist-darleen-mackay has been reidentified and named as PractitionerRole-renalmedicine-mackay-darleen
PractitionerRole-surgeon-david-surgeon (removed from the IG and replaced with PractitionerRole-surgeon-chau-fryer (SA test data))
- PractitionerRole-surgeon-david-surgeon already removed
- PractitionerRole-surgeon-chau-fryer has been reidentified and named as PractitionerRole-surgeongeneral-fryer-chau
Practitioner-levin-henry (removed from the IG and replaced with Practitioner-darleen-mackay)
- Practitioner-levin-henry already removed
- Practitioner-darleen-mackay has been reidentified and named as Practitioner-mackay-darleen
Practitioner-surgeon-david (removed from the IG and replaced with Practitioner-chau-fryer (SA test data))
- Practitioner-surgeon-david already removed
- Practitioner-chau-fryer has been reidentified and named as Practitioner-fryer-chau
Organization-dva-au
- already removed
Organization-health-au
- already removed

**Comment by heathfrankel** [comment]
- PractitionerRole-retail-pharmacist
  - removed already and replaced with PractitionerRole-retailpharmacist-ford-dean
- PractitionerRole-sandyson-sandy-nurse
  - removed already and replaced with PractitionerRole-registerednurses-sinclair-forrest
- PractitionerRole-gp-primary-peter
  - removed already and replaced with PractitionerRole-generalpractitioner-harding-diana
- Practitioner-primary-peter
  - removed already
- PractitionerRole-np-nurse-nancy
  - removed already and replaced with PractitionerRole-nursepractitioner-osmond-deadra
- Practitioner-nurse-nancy
  - removed already
- Practitionecardiolor-cardy-igist
  - PractitionerRole-cardiologist-cardy-igist already removed and replaced with PractitionerRole-cardiologist-felmingham-emma
  - Practitioner-cardy-igist already removed
- Organization-hospital-au
  - Organization-hospital-au already removed and replaced with Organization-barney-view-private-hospital
- Organization-hospital-int
  - already removed
- Organization-pharmacy
  - already removed and replaced with Organization-east-mackay-pharmacy
- Location-pharmacy - remove existing and generate from SA test data
  - already removed and replaced with Location-east-mackay-pharmacy
- Location-au-hospital - remove existing and generate from SA test data
  - already removed and replaced with Location-barney-view-private-hospital
- Location-au-hospital-pharm-out - remove existing and generate from SA test data
  - **this has been retained for air-covid-1 Immunization**
- Location-au-hospital-sw-physio - remove existing and generate from SA test data
  - already removed

**Comment by heathfrankel** [comment]
- PractitionerRole-audiologist-bradley-jill
  - **currently retained** for SNOMED code coding (only one with only a SCT code). This could be removed now if we decide 
- Practitioner-bradley-jill
  - **currently retained** as above
- PractitionerRole-dietician-tan-patricia
  - already removed
- Organization-adv-hearing-care (Audiology service organization provided but not linked to a provider)
  - **currently retained** for PractitionerRole-audiologist-bradley-jill as above

**Comment by heathfrankel** [comment]
- encounter-discharge-1.xml
  - we are using reference Patient/irvine-ronny-lawrence (compared with ronny-irvine) and Location/barney-view-private-hospital and Organization/barney-view-private-hospital (compared with Location/murrabit-hospital and Organization/murrabit-hospital)
- hearing-threshold-1.xml
  - added - used reference Patient/irvine-ronny-lawrence (compared with ronny-irvine)
- medicationrequest-paracetamol-codeine.xml
  - exists already - uses Patient/baratz-toni (compared with Patient/bennelong-anne)
  - removed note, dispenseRequest and substitution elements
- medicationrequest-reaptan.xml
  - exists 
  - uses Patient/howe-deangelo (compared with Patient/wang-li)
  - uses PractitionerRole/cardiothoracicsurgeon-manning-meg (compared with PractitionerRole/surgeon-chau-fryer)
  - moved medicationCodeableConcept to contained Medication.code and provide code.text rather than coding.display 
  - reasonCode is Hypertension (compared with "Pain management", which is wrong)
  - dosage is 1 tablet daily (compared with "1-2 tablets every 4-6 hours as needed for pain", which is wrong)
  - removed dispenseRequest and substitution elements
- procedure-dialysis.xml
  - already exists
  - references Patient/irvine-ronny-lawrence (compared with Patient/ronny-irvine)
  - references PractitionerRole/renalmedicine-mackay-darleen (compared with PractitionerRole/nephrologist-darleen-mackay)
  - removed Encounter reference
- procedure-stentinsertion.xml
  - already exists
  - references Patient/howe-deangelo (compared with Patient/wang-li)
  - references PractitionerRole/cardiothoracicsurgeon-manning-meg (compared with PractitionerRole/surgeon-chau-fryer)
  - references Location/murrabit-public-hopsital (compared with Location/murrabit-hospital)
  - added code.text
  - removed Encounter
